[package]
name = "wasm-shrink-tracker"
version = "0.1.0"
edition = "2018"

[dependencies]
structopt = "0.3"
tempfile = "3.0"
log = "0.4"
env_logger = "0.8"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"